In [47]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

In [48]:
df=pd.read_csv("kidney-stone-dataset.csv")
df

    Unnamed: 0   gravity        ph  osmo       cond  urea      calc  target
0            0  1.021000  4.910000   725  14.000000   443  2.450000       0
1            1  1.017000  5.740000   577  20.000000   296  4.490000       0
2            2  1.008000  7.200000   321  14.900000   101  2.360000       0
3            3  1.011000  5.510000   408  12.600000   224  2.150000       0
4            4  1.005000  6.520000   187   7.500000    91  1.160000       0
..         ...       ...       ...   ...        ...   ...       ...     ...
85          85  1.021452  5.556081   756  24.241481   367  7.669120       1
86          86  1.016501  6.900257   549  20.549790   204  5.775256       1
87          87  1.032754  5.443491  1085  23.188653   576  8.664169       1
88          88  1.023870  5.106433   325  12.124689    50  0.781620       1
89          89  1.013723  6.308943   472  16.907792   174  2.556405       1

[90 rows x 8 columns]

In [49]:
df.shape

(90, 8)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  90 non-null     int64
 1   gravity     90 non-null     float64
 2   ph          90 non-null     float64
 3   osmo        90 non-null     int64
 4   cond        90 non-null     float64
 5   urea        90 non-null     int64
 6   calc        90 non-null     float64
 7   target      90 non-null     int64
dtypes: float64(4), int64(4)
memory usage: 5.8 KB

In [51]:
df.describe()

,Unnamed: 0,gravity,ph,osmo,cond,urea,calc,target
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,44.500000,1.017952,6.036651,602.333333,20.621687,258.200000,4.017788,0.500000
std,26.124701,0.006780,0.711801,238.459805,7.654448,135.381127,3.016273,0.502801
min,0.000000,1.005000,4.760000,187.000000,5.100000,10.000000,0.170000,0.000000
25%,22.250000,1.012258,5.536520,411.500000,14.150000,148.250000,1.412500,0.000000
50%,44.500000,1.018000,5.936247,572.000000,21.177172,231.500000,3.230000,0.500000
75%,66.750000,1.023000,6.490000,778.000000,26.075000,366.250000,5.965127,1.000000
max,89.000000,1.034000,7.940000,1236.000000,38.000000,620.000000,13.000000,1.000000

In [52]:
df.head()

   Unnamed: 0  gravity    ph  osmo  cond  urea  calc  target
0           0    1.021  4.91   725  14.0   443  2.45       0
1           1    1.017  5.74   577  20.0   296  4.49       0
2           2    1.008  7.20   321  14.9   101  2.36       0
3           3    1.011  5.51   408  12.6   224  2.15       0
4           4    1.005  6.52   187   7.5    91  1.16       0

In [53]:
df.tail()

    Unnamed: 0   gravity        ph  osmo       cond  urea      calc  target
85          85  1.021452  5.556081   756  24.241481   367  7.669120       1
86          86  1.016501  6.900257   549  20.549790   204  5.775256       1
87          87  1.032754  5.443491  1085  23.188653   576  8.664169       1
88          88  1.023870  5.106433   325  12.124689    50  0.781620       1
89          89  1.013723  6.308943   472  16.907792   174  2.556405       1

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.isnull().sum()

Unnamed: 0    0
gravity       0
ph            0
osmo          0
cond          0
urea          0
calc          0
target        0
dtype: int64

In [56]:

X = df.drop(columns=['Unnamed: 0', 'target'])


y = df['target']

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [72]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [73]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [74]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [75]:




print(f" Train Accuracy: {clf.score(x_train_scaled, y_train):.4f}")
print(f" Test Accuracy: {clf.score(x_test_scaled, y_test):.4f}")

 Train Accuracy: 0.8333
 Test Accuracy: 0.6111

In [76]:
from sklearn.metrics import classification_report, accuracy_score


y_pred = clf.predict(x_test_scaled)
acc = accuracy_score(y_test, y_pred)
print(f"Overall Accuracy: {acc:.4f}\n")

Overall Accuracy: 0.6111

In [77]:
# 3. Print the full classification report breakdown
print("Full Classification Report:")
print(classification_report(y_test, y_pred))

Full Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.67      0.70        12
           1       0.43      0.50      0.46         6

    accuracy                           0.61        18
   macro avg       0.58      0.58      0.58        18
weighted avg       0.63      0.61      0.62        18