In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("mtcars2.csv")
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [4]:
df.shape

(32, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S.No        32 non-null     int64
 1   Unnamed: 1  32 non-null     object
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64
 10  am          32 non-null     int64
 11  gear        32 non-null     int64
 12  carb        32 non-null     int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB

In [6]:
df.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [8]:
df.min(numeric_only=True)

S.No     1.000
mpg     10.400
cyl      4.000
disp    71.100
hp      52.000
drat     2.760
wt       1.513
qsec    14.500
vs       0.000
am       0.000
gear     3.000
carb     1.000
dtype: float64

In [9]:
df.max(numeric_only=True)

S.No     32.000
mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

In [10]:
df.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [11]:
df["vs"].mean()

np.float64(0.4375)

In [12]:
df["vs"].median()

0.0

In [13]:
df["vs"].std()

0.5040161287741853

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

In [43]:

df = df.dropna()

In [86]:

y = df['carb']

X = df.drop(columns=['carb', 'S.No', 'Unnamed: 1'])

In [87]:
X

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4

In [88]:
y

0     4
1     4
2     1
3     1
4     2
6     4
7     2
8     2
9     4
10    4
11    3
12    3
13    3
14    4
15    4
16    4
18    2
19    1
20    1
21    2
22    2
23    4
24    2
26    2
27    2
28    4
29    6
30    8
31    2
Name: carb, dtype: int64

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [91]:
x_train

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4

In [92]:
x_test

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4

In [93]:
y_train

23    4
0     4
29    6
14    4
16    4
12    3
19    1
1     4
4     2
6     4
2     1
27    2
3     1
26    2
28    4
20    1
31    2
22    2
8     2
11    3
15    4
21    2
7     2
Name: carb, dtype: int64

In [94]:
y_test

30    8
18    2
13    3
24    2
9     4
10    4
Name: carb, dtype: int64

In [95]:
from sklearn.preprocessing import StandardScaler

In [96]:
scaler=StandardScaler()
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)
X_test

array([[-0.78789106,  0.96673649,  0.45642601,  3.06377423, -0.02673419,
         0.27821412, -1.70577109, -0.73029674,  1.24721913,  1.77797194],
       [ 1.91366764, -1.25675744, -1.34862164, -1.64399406,  2.92047936,
        -1.66341215,  0.44818299,  1.36930639,  1.24721913,  0.45883147],
       [-0.75280588,  0.96673649,  0.25452987,  0.48531457, -1.02327402,
         0.48677756,  0.16245439, -0.73029674, -0.80178373, -0.860309  ],
       [-0.05110232,  0.96673649,  1.24958942,  0.40213845, -1.00207104,
         0.55133291, -0.35954979, -0.73029674, -0.80178373, -0.860309  ],
       [-0.05110232, -0.14501047, -0.61234166, -0.46289318,  0.77897887,
         0.14910343,  0.32729781,  1.36930639, -0.80178373,  0.45883147],
       [-0.29669857, -0.14501047, -0.61234166, -0.46289318,  0.77897887,
         0.14910343,  0.65698466,  1.36930639, -0.80178373,  0.45883147]])

In [97]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [98]:
regression=LinearRegression()
regression.fit(X_train,y_train)
y_pred=regression.predict(X_test)

score=r2_score(y_test,y_pred)
print(score)

0.5899970606728989