In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel(r"C:/Users\Asus/Downloads/movies dataset.xlsx")
df

,Movie Name,Release Period,Whether Remake,Whether Franchise,Genre,New Actor,New Director,New Music Director,Lead Star,Director,Music Director,Number of Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [3]:
df.shape

(1698, 14)

In [6]:
df.describe()

       Number of Screens  Revenue(INR)   Budget(INR)
count        1698.000000  1.698000e+03  1.698000e+03
mean          553.831567  1.501674e+08  2.377287e+08
std           782.951839  2.434838e+08  6.134398e+08
min             1.000000  3.250000e+05  7.250000e+03
25%            30.000000  1.500000e+07  1.150000e+06
50%           200.000000  5.500000e+07  1.240000e+07
75%           800.000000  1.900000e+08  1.778325e+08
max          4600.000000  2.100000e+09  8.016120e+09

In [18]:
df.head()

,Movie Name,Release Period,Whether Remake,Whether Franchise,Genre,New Actor,New Director,New Music Director,Lead Star,Director,Music Director,Number of Screens,Revenue(INR),Budget(INR),combined_features
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000,suspense Jeet Goswami Ravi Varma
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000,drama Karan Bhanushali Sagar Ballary
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000,thriller Mahie Gill Ram Gopal Verma
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000,drama Aadar Jain Habib Faisal
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000,adult Aadil Khan Aadil Khan

In [19]:
df.tail()

,Movie Name,Release Period,Whether Remake,Whether Franchise,Genre,New Actor,New Director,New Music Director,Lead Star,Director,Music Director,Number of Screens,Revenue(INR),Budget(INR),combined_features
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500,action Zayed Khan Vikram Chopra
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000,drama Zeenat Aman Sanghamitra Chaudhuri
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000,drama Zeenat Aman Sanjay Sharma
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000,drama Zulfi Sayed Akbar Khan
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000,comedy Zulfi Sayed Partho Ghosh

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie Name          1698 non-null   object
 1   Release Period      1698 non-null   object
 2   Whether Remake      1698 non-null   object
 3   Whether Franchise   1698 non-null   object
 4   Genre               1698 non-null   object
 5   New Actor           1698 non-null   object
 6   New Director        1698 non-null   object
 7   New Music Director  1698 non-null   object
 8   Lead Star           1698 non-null   object
 9   Director            1698 non-null   object
 10  Music Director      1698 non-null   object
 11  Number of Screens   1698 non-null   int64
 12  Revenue(INR)        1698 non-null   int64
 13  Budget(INR)         1698 non-null   int64
dtypes: int64(3), object(11)
memory usage: 185.8+ KB

In [8]:
df.shape

(1698, 14)

In [9]:
df.isnull().sum()

Movie Name            0
Release Period        0
Whether Remake        0
Whether Franchise     0
Genre                 0
New Actor             0
New Director          0
New Music Director    0
Lead Star             0
Director              0
Music Director        0
Number of Screens     0
Revenue(INR)          0
Budget(INR)           0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(2)

In [11]:
df.drop_duplicates()

,Movie Name,Release Period,Whether Remake,Whether Franchise,Genre,New Actor,New Director,New Music Director,Lead Star,Director,Music Director,Number of Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [12]:
df[['Genre', 'Lead Star', 'Director']].isnull().sum()

Genre        0
Lead Star    0
Director     0
dtype: int64

In [13]:
df['combined_features'] = df['Genre'] + " " + df['Lead Star'] + " " + df['Director']
df['combined_features'].head()

0        suspense Jeet Goswami Ravi Varma
1    drama Karan Bhanushali Sagar Ballary
2     thriller Mahie Gill Ram Gopal Verma
3           drama Aadar Jain Habib Faisal
4             adult Aadil Khan Aadil Khan
Name: combined_features, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Convert the text into numbers
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])

# Compute the similarity scores between all movies
similarity_scores = cosine_similarity(count_matrix)

In [15]:
def get_recommendations(movie_title, top_n=5):
    # Find the row index of the requested movie
    try:
        movie_idx = df[df['Movie Name'].str.lower() == movie_title.lower()].index[0]
    except IndexError:
        return "Movie not found in the dataset. Check your spelling!"
    
    # Get all similarity scores for this movie
    sim_scores = list(enumerate(similarity_scores[movie_idx]))
    
    # Sort movies based on similarity scores (highest first)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices of the top movies (skipping the 0th index because it's the movie itself)
    top_movies_indices = [i[0] for i in sim_scores[1:top_n+1]]
    
    # Return the titles
    return df['Movie Name'].iloc[top_movies_indices]

In [16]:
get_recommendations("Fight Club")

1636      Trump Card
1692           Speed
1243       Dabangg 2
1247    Ek Tha Tiger
1259          Jai Ho
Name: Movie Name, dtype: object